---
- name: Install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: Install mosh pre-reqs
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - protobuf-compiler
      - make
      - zlib-devel
      - ncurses-devel
      - openssl-devel
      - protobuf-devel
